"""Run with python3 -m sports from the repository root."""

import argparse
import json
import sqlite3

from .analytics import analyze
from .demo import demo_rows
from .server import make_server
from .store import DEFAULT_DB, Store, read_csv


def main(argv=None):
    parser = argparse.ArgumentParser(description="Sports statistics and probability prototype")
    parser.add_argument("--db", default=str(DEFAULT_DB), help="SQLite database path")
    commands = parser.add_subparsers(dest="command", required=True)
    demo = commands.add_parser("demo", help="Generate fictional basketball data")
    demo.add_argument("--replace", action="store_true")
    ingest = commands.add_parser("import", help="Import a permitted historical CSV")
    ingest.add_argument("csv")
    ingest.add_argument("--source", required=True, help="Dataset source URL")
    ingest.add_argument("--rights", required=True, help="License or permission statement")
    ingest.add_argument("--replace", action="store_true")
    commands.add_parser("options", help="List available teams, players, and opponents")
    analysis = commands.add_parser("analyze", help="Analyze historical points and evaluate a baseline")
    analysis.add_argument("--team", required=True)
    analysis.add_argument("--player")
    analysis.add_argument("--opponent")
    analysis.add_argument("--threshold", type=float, default=20.5)
    serve = commands.add_parser("serve", help="Start the local dashboard and JSON API")
    serve.add_argument("--host", default="127.0.0.1")
    serve.add_argument("--port", type=int, default=8000)
    arguments = parser.parse_args(argv)
    try:
        store = Store(arguments.db)
        if arguments.command == "demo":
            result = store.replace(demo_rows(), kind="synthetic", source="Generated by sports/demo.py",
                                   rights="Fictional data generated for this prototype",
                                   replace=arguments.replace)
        elif arguments.command == "import":
            result = store.replace(read_csv(arguments.csv), kind="imported", source=arguments.source,
                                   rights=arguments.rights, replace=arguments.replace)
        elif arguments.command == "options":
            result = store.options()
        elif arguments.command == "analyze":
            result = analyze(store, arguments.team, arguments.player, arguments.opponent,
                             arguments.threshold)
        else:
            if not 0 < arguments.port <= 65535:
                raise ValueError("Port must be between 1 and 65535")
            server = make_server(store, arguments.host, arguments.port)
            print(f"Sports dashboard: http://{arguments.host}:{arguments.port}", flush=True)
            try:
                server.serve_forever()
            except KeyboardInterrupt:
                pass
            finally:
                server.server_close()
            return 0
        print(json.dumps(result, indent=2, allow_nan=False))
        return 0
    except (ValueError, OSError, sqlite3.Error) as error:
        parser.exit(2, f"Error: {error}\n")


if __name__ == "__main__":
    raise SystemExit(main())
